#!/usr/bin/env node
'use strict';
/* Checks the things that decide whether the page survives poll close.

   The page itself is on a CDN and executes nothing, so it is not the fragile
   part. The fragile part is the WordPress post that wraps it: that is one
   request per reader, and if it is not served from a page cache then every
   reader is a PHP execution. At poll close that saturates PHP workers, which
   the host then reports as a CPU problem.

   Run it days before the election, and again after the last edit to the post.

   Usage:
     node scripts/check-embed.js
     node scripts/check-embed.js --url https://example.org/post/
*/

const { loadConfig } = require('./lib/config');
const { collectCharts, datawrapperApiBase } = require('./lib/charts');

const errors = [];
const warnings = [];
const err = m => errors.push(m);
const warn = m => warnings.push(m);

const TRACKING = 'utm_source=twitter&utm_medium=social&utm_campaign=election&mc_eid=a1b2c3d4e5&fbclid=xyz';

/* Every stack names its cache header differently, and `age` is the one piece of
   standard HTTP that betrays a cache regardless. */
const CACHE_HEADERS = [
  'x-cache-status', 'x-cache', 'cf-cache-status', 'x-litespeed-cache',
  'x-proxy-cache', 'x-kinsta-cache', 'x-varnish-cache', 'x-nginx-cache',
];

function cacheVerdict(headers) {
  for (const name of CACHE_HEADERS) {
    const v = headers.get(name);
    if (v) return { header: `${name}: ${v}`, hit: /hit/i.test(v) };
  }
  const age = Number(headers.get('age'));
  if (Number.isFinite(age) && age > 0) return { header: `age: ${age}`, hit: true };
  return { header: null, hit: false };
}

/* A cached HTML response should not have been generated by PHP. These headers
   only exist because WordPress booted to produce this response. */
function phpEvidence(headers) {
  const found = [];
  const powered = headers.get('x-powered-by');
  if (powered && /php/i.test(powered)) found.push(powered);
  if (headers.get('x-pingback')) found.push('X-Pingback');
  const link = headers.get('link');
  if (link && /wp-json/.test(link)) found.push('Link: wp-json');
  return found;
}

function cookieNames(headers) {
  const raw = typeof headers.getSetCookie === 'function'
    ? headers.getSetCookie()
    : [headers.get('set-cookie')].filter(Boolean);
  return raw.map(c => String(c).split('=')[0].trim()).filter(Boolean);
}

async function probe(url, { wantBody = false } = {}) {
  const res = await fetch(url, {
    redirect: 'follow',
    headers: {
      'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36',
    },
  });
  const body = wantBody ? await res.text() : (await res.arrayBuffer(), null);
  return {
    status: res.status,
    cache: cacheVerdict(res.headers),
    php: phpEvidence(res.headers),
    cookies: cookieNames(res.headers),
    body,
  };
}

function line(label, p) {
  const bits = [
    `HTTP ${p.status}`,
    `cache=${p.cache.header || 'no cache header'}`,
    `php=${p.php.length ? p.php.join(' + ') : 'no'}`,
    `set-cookie=${p.cookies.length ? p.cookies.join(', ') : 'none'}`,
  ];
  console.log(`  ${label}  ${bits.join('  |  ')}`);
}

async function checkPost(url) {
  console.log(`\nWordPress post  ${url}`);

  const first = await probe(url, { wantBody: true });
  const second = await probe(url);
  line('request 1:', first);
  line('request 2:', second);

  if (first.status >= 400) {
    err(`the post returned HTTP ${first.status} — nothing else here is meaningful`);
    return { body: first.body, cleanHit: false };
  }

  /* LiteSpeed and similar layers answer an unfamiliar client with a small
     reCAPTCHA interstitial instead of the page. It returns 200, so without
     checking the body every header below would be read off the challenge rather
     than the article. Worth knowing for its own sake too: whatever triggers it
     for a script can trigger it for readers under load. */
  if (first.body && /Bot Verification|lsrecaptcha|g-recaptcha/i.test(first.body) && first.body.length < 20000) {
    err(
      `the post answered with a bot-verification page (${first.body.length} bytes), not the article. ` +
      'Every reading below is off that challenge, not the post. Ask the host what triggers it and whether ' +
      'it can fire on ordinary readers during a traffic spike.'
    );
    return { body: null, cleanHit: false };
  }

  const cleanHit = second.cache.hit;

  if (!cleanHit) {
    err(
      'the second request was NOT served from cache. Every reader of this post is a PHP execution, ' +
      'so poll close turns readers directly into CPU load. This is the one thing to fix.'
    );
  } else {
    console.log('  ok: the second request came from cache');
  }

  if (second.php.length) {
    err(`the response carries PHP-generated headers (${second.php.join(', ')}), so WordPress booted for it`);
  }

  if (second.cookies.length) {
    err(
      `the response sets a cookie (${second.cookies.join(', ')}). Practically every HTTP cache refuses to ` +
      'store a response with Set-Cookie, because it looks reader-specific. Remove it for anonymous readers ' +
      'or exclude it from the cache key at the edge.'
    );
  }

  return { body: first.body, cleanHit };
}

async function checkTracking(url, cleanHit) {
  const target = url + (url.includes('?') ? '&' : '?') + TRACKING;
  console.log(`\nTracking parameters  ?${TRACKING.slice(0, 48)}…`);

  if (!cleanHit) {
    console.log('  skipped: the clean URL is not cached either, so fix that first');
    return;
  }

  await probe(target);
  const second = await probe(target);
  line('request 2:', second);

  if (!second.cache.hit) {
    err(
      'a URL carrying tracking parameters is not cached, while the clean URL is. Election-night traffic is ' +
      'almost entirely social and newsletter referrals, so in practice nearly every reader arrives on one of ' +
      'these URLs and bypasses the cache. Strip utm_*, fbclid, gclid, mc_cid and mc_eid from the cache key.'
    );
  } else {
    warn(
      'tracking parameters are cached, but under their own key. Fixed campaign parameters are then only ' +
      'wasteful, but Mailchimp\'s mc_eid is unique per recipient — so a newsletter send still misses on every ' +
      'single reader. Strip these from the cache key rather than caching each variant.'
    );
  }
}

function checkEmbed(body, config) {
  const pagesUrl = config.page && config.page.pagesUrl;
  const key = (config.page && config.page.frameMessageKey) || 'electionFrameHeight';
  console.log('\nEmbed');

  if (!body) { console.log('  skipped: no post HTML'); return; }

  if (!pagesUrl || /^TODO/.test(pagesUrl)) {
    warn('page.pagesUrl is not set, so the embed cannot be checked and there is no fallback link to publish');
    return;
  }

  const host = pagesUrl.replace(/^https?:\/\//, '').replace(/\/+$/, '');
  if (body.includes(host)) console.log(`  ok: the post embeds ${pagesUrl}`);
  else err(`the post does not reference ${pagesUrl} — check the iframe src`);

  /* The parent snippet is usually copied from the previous election's post, and
     it then listens for that election's message key while this page posts a
     different one. The embed stays stuck at its initial height. */
  if (body.includes(key)) console.log(`  ok: the post listens for "${key}"`);
  else err(`the post never mentions "${key}", so the iframe will not resize. The listener in the post and page.frameMessageKey must match.`);
}

/* Reads each configured chart's published bundle and reports what it actually
   draws its data from.

   This is the one thing nobody verifies by hand seven times, and it fails in
   the worst way: a chart whose data was uploaded as a file rather than linked
   to the Sheet looks completely normal and simply never updates, all evening,
   with nothing anywhere reporting a fault. Republishing it does not help — the
   data is baked in at publish time. */
async function checkChartSources(config) {
  const charts = collectCharts(config).filter(c => !/^TODO/i.test(c.id));
  if (!charts.length) return;
  const sheetId = (config.sheet && config.sheet.id) || '';
  const token = process.env.DATAWRAPPER_TOKEN;
  console.log('\nChart data sources');

  if (!token) {
    /* Scraping the published bundle for the dataset URL does not work: the URL
       often lives in a JS chunk the page loads separately, so its absence from
       the HTML proves nothing. An earlier version of this check reported it as
       an error and cried wolf on charts that were correctly linked. The API is
       the only authoritative answer, so without a token this says nothing
       rather than something wrong. */
    warn('DATAWRAPPER_TOKEN is not set, so chart data sources could not be checked. Set it and re-run — this is the check that catches a chart still reading the previous election\'s Sheet.');
    return;
  }

  const apiBase = datawrapperApiBase(config);
  for (const chart of charts) {
    const where = `${chart.section} · ${chart.id}`;
    let body;
    try {
      const res = await fetch(`${apiBase}/charts/${chart.id}`, { headers: { Authorization: `Bearer ${token}` } });
      if (!res.ok) { err(`${where}: GET /charts/${chart.id} returned HTTP ${res.status}`); continue; }
      body = await res.json();
    } catch (e) {
      warn(`${where} could not be read from the API: ${e.message}`);
      continue;
    }

    /* The version in the embed URL is the one readers get. Republishing makes a
       new one, so a config pinned to an older version keeps serving that older
       render however many times the chart is updated. */
    const live = body.publicVersion;
    if (live != null && Number(chart.version) !== Number(live)) {
      err(`${where} is pinned to version ${chart.version} but the chart is published at version ${live}. The page is serving the older render.`);
    }

    const d = (body.metadata && body.metadata.data) || {};
    const url = typeof d['external-data'] === 'string' ? d['external-data']
              : typeof d.externalData === 'string' ? d.externalData : null;

    if (!url) {
      const msg = `${where} has no linked dataset — its data is an uploaded file, frozen at publish time`;
      (chart.live ? err : warn)(chart.live
        ? `${msg}. Fix it in Datawrapper: Upload data -> Link external dataset.`
        : `${msg}. Fine for a static chart.`);
      continue;
    }

    const m = url.match(/spreadsheets\/d\/([A-Za-z0-9_-]+)/);
    const tab = (url.match(/gid=\d+|sheet=[^&]*/) || ['no tab parameter'])[0];
    if (m && m[1] === sheetId) {
      console.log(`  ok: ${where} reads this election's Sheet (${tab}), version ${chart.version}`);
    } else {
      const msg = `${where} reads ${m ? `a different spreadsheet (${m[1]}, ${tab})` : url}`;
      (chart.live ? err : warn)(chart.live
        ? `${msg} while marked live: true. A copied chart still reading the previous election's Sheet looks fine until the numbers are wrong.`
        : `${msg}. Expected for a chart maintained outside this page.`);
    }
  }
}

async function checkPages(config) {
  const pagesUrl = config.page && config.page.pagesUrl;
  if (!pagesUrl || /^TODO/.test(pagesUrl)) return;
  const base = pagesUrl.replace(/\/+$/, '');
  console.log(`\nPublished page  ${base}`);

  for (const file of ['config.json', 'data/parties.json']) {
    try {
      const res = await fetch(`${base}/${file}`, { headers: { 'Cache-Control': 'no-cache' } });
      if (res.ok) console.log(`  ok: ${file}`);
      else err(`${base}/${file} returned HTTP ${res.status} — the page cannot render without it`);
    } catch (e) {
      err(`${base}/${file} could not be fetched: ${e.message}`);
    }
  }
}

function arg(name) {
  const i = process.argv.indexOf(name);
  return i === -1 ? null : process.argv[i + 1];
}

async function main() {
  const config = loadConfig();
  const url = arg('--url') || (config.page && config.page.postUrl);

  let body = null;
  if (!url || /^TODO/.test(url)) {
    warn('page.postUrl is not set, so the WordPress post was not checked — that is the part that falls over at poll close');
  } else {
    const post = await checkPost(url);
    body = post.body;
    await checkTracking(url, post.cleanHit);
  }

  checkEmbed(body, config);
  await checkChartSources(config);
  await checkPages(config);

  console.log('');
  for (const w of warnings) console.log(`WARN   ${w}`);
  for (const e of errors) console.error(`ERROR  ${e}`);
  console.log(`\n${errors.length} error(s), ${warnings.length} warning(s)`);
  if (errors.length) process.exit(1);
  console.log('the embed and its cache look ready for poll close');
}

if (require.main === module) {
  main().catch(e => { console.error(`check-embed failed: ${e.message}`); process.exit(1); });
}

module.exports = { cacheVerdict, phpEvidence, cookieNames, TRACKING };
